Add rule for CVE-2024-4577
chainguard-dev/bincapz pull request #266
Opened 2024-06-10 19:49 UTC by egibs

This PR is an attempt to detect the conditions for `CVE-2024-4577` --
- https://www.wiz.io/blog/critical-rce-php-cgi-vulnerability
- https://github.com/watchtowrlabs/CVE-2024-4577
- https://labs.watchtowr.com/no-way-php-strikes-again-cve-2024-4577
- https://pentesterlab.com/exercises/cve-2012-1823

This will match the specific POC request which matches this from the `pentesterlab` post for `CVE-2012-1823`:
![CleanShot 2024-06-10 at 14 38 34@2x](https://github.com/chainguard-dev/bincapz/assets/20933572/652a63a0-bb5d-4698-b374-700ebc80c2cb)

`allow_url_include` and `auto_prepend_file` were covered in the Dodgy PHP rules (separately), but I didn't see a soft-hyphen rule unless searching failed me.

2024-06-10 19:57 UTC, tstromberg requested changes

2024-06-10 19:57 UTC, tstromberg commented on rules/combo/backdoor/php.yara
> +    $url_pattern = /\?%ADd\+allow_url_include%3d1\+(%ADd|-)[d+]\+auto_prepend_file%3dphp:\/\/input/ nocase
- I think you can leave out `nocase` here. See https://github.com/Neo23x0/YARA-Performance-Guidelines/ for why it should be avoided when possible.
- Removing the leading `\?%ADd\+` portion may yield more hits without adding false positives

2024-06-10 19:57 UTC, tstromberg commented on rules/combo/backdoor/php.yara
> +rule php_cgi_argument_injection : critical {
Technically this isn't a "combo" rule to match a backdoor.

What do you think about a new directory for these kinds of rules, for example: `exploits/php`?

2024-06-10 20:00 UTC, egibs commented on rules/combo/backdoor/php.yara
> +rule php_cgi_argument_injection : critical {
I think that makes sense -- TBH the categorizations are still something I'm getting up to speed on 😅

2024-06-10 20:09 UTC, egibs commented on rules/combo/backdoor/php.yara
> +rule php_cgi_argument_injection : critical {
Moved in [`8eb5607` (#266)](https://github.com/chainguard-dev/bincapz/pull/266/commits/8eb56076badf207af55fabb41c89a4377dc438e6).

2024-06-10 20:10 UTC, egibs commented on rules/combo/backdoor/php.yara
> +    $url_pattern = /\?%ADd\+allow_url_include%3d1\+(%ADd|-)[d+]\+auto_prepend_file%3dphp:\/\/input/ nocase
Removed `nocase` in [`f17f84d` (#266)](https://github.com/chainguard-dev/bincapz/pull/266/commits/f17f84d67fb09ae9e294b6b4fa020cc9c4cc5240), though 👍🏻

2024-06-11 21:24 UTC, tstromberg approved these changes

2024-06-11 21:55 UTC, merged